---
metric_prefix: "cloudwatch"
influx_options:
  influx_host: "10.168.192.192"
  influx_database: cloud_watch
  influx_ssl: false
  influx_verify_ssl: false
  influx_ssl_ca_cert: "/path/to/certs"
  influx_username: "cloud_watch"
  influx_password: "zaq1xsw2"

metric_types:
## EC2 Metrics
-
  namespace: "AWS/EC2"
  ec2_tag_key: "Type"
  ec2_tag_value: "AP"
  metrics:
    -
      name: "CPUUtilization"
      unit: "Percent"
      statistics:
        - Average
    -
      name: "NetworkIn"
      unit: "Bytes"
      statistics:
        - Average
    -
      name: "NetworkOut"
      unit: "Bytes"
      statistics:
        - Average
